"""
Tradeloop — AI Extraction Result Model

Stores structured extraction results generated by LLM / NLP engines.
Tracks field-level confidence, quotation evidence citations, and human review status.
"""

import enum
import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Any, Dict, Optional
from sqlalchemy import DateTime, Enum, ForeignKey, String
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import BaseModel

if TYPE_CHECKING:
    from app.models.artifact import Artifact
    from app.models.deal import Deal
    from app.models.organisation import Organisation
    from app.models.user import User


class ExtractionStatus(str, enum.Enum):
    """Workflow state of the AI extraction."""
    PENDING_REVIEW = "PENDING_REVIEW"
    CONFIRMED = "CONFIRMED"
    REJECTED = "REJECTED"
    EDITED = "EDITED"


class ExtractionResult(BaseModel):
    """
    Structured extraction payload with confidence scores and evidence quotes.
    """

    __tablename__ = "extraction_results"

    organisation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organisations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    deal_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("deals.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    artifact_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("artifacts.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    model_name: Mapped[str] = mapped_column(String(100), default="ai-extractor-v1", nullable=False)
    model_version: Mapped[str] = mapped_column(String(50), default="1.0", nullable=False)

    # Dictionary of extracted fields: { field_name: { value, confidence, evidence, status } }
    extracted_data: Mapped[Dict[str, Any]] = mapped_column(
        JSONB,
        default=dict,
        nullable=False,
    )

    status: Mapped[ExtractionStatus] = mapped_column(
        Enum(ExtractionStatus, name="extraction_status_enum", native_enum=False),
        default=ExtractionStatus.PENDING_REVIEW,
        nullable=False,
    )

    reviewed_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )

    reviewed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    # Relationships
    organisation: Mapped["Organisation"] = relationship("Organisation", lazy="joined")
    deal: Mapped["Deal"] = relationship("Deal", lazy="joined")
    artifact: Mapped[Optional["Artifact"]] = relationship("Artifact", lazy="joined")
    reviewer: Mapped[Optional["User"]] = relationship("User", lazy="joined")

    def __repr__(self) -> str:
        return f"<ExtractionResult id={self.id} deal={self.deal_id} status={self.status}>"
